export enum Role {
  IT_ADMIN = "IT_ADMIN",
  HOSPITAL_ADMIN = "HOSPITAL_ADMIN",
  FRONT_DESK = "FRONT_DESK",
  PATIENT_COORDINATOR = "PATIENT_COORDINATOR",
  DOCTOR = "DOCTOR",
  NURSE = "NURSE",
  RECORDS_STAFF = "RECORDS_STAFF",
  CONTENT_ADMIN = "CONTENT_ADMIN",
  PATIENT = "PATIENT",
}

