import { Permission } from "@/enums/permission";
import { Role } from "@/enums/role";
import type { RoleDefinition } from "@/types/auth";

export const roleDefinitions: RoleDefinition[] = [
  { role: Role.IT_ADMIN, label: "IT Administrator", description: "Full system access." },
  { role: Role.HOSPITAL_ADMIN, label: "Hospital Administrator", description: "Operational hospital management." },
  { role: Role.FRONT_DESK, label: "Front Desk", description: "Patient registration, appointment handling, and queue creation." },
  { role: Role.PATIENT_COORDINATOR, label: "Patient Coordinator", description: "Checked-in visit monitoring and doctor assignment." },
  { role: Role.DOCTOR, label: "Doctor", description: "Own assigned patients and doctor queue." },
  { role: Role.NURSE, label: "Nurse", description: "Limited patient and queue operational workflow." },
  { role: Role.RECORDS_STAFF, label: "Records Staff", description: "Future records and document workflow." },
  { role: Role.CONTENT_ADMIN, label: "Content Administrator", description: "Public website content management." },
  { role: Role.PATIENT, label: "Patient", description: "Own portal information only." },
];

export const permissionLabels: Record<Permission, string> = {
  [Permission.DASHBOARD_VIEW]: "View Dashboard",
  [Permission.PATIENT_VIEW]: "View Patients",
  [Permission.PATIENT_CREATE]: "Create Patient",
  [Permission.PATIENT_UPDATE]: "Edit Patient",
  [Permission.APPOINTMENT_VIEW]: "View Appointments",
  [Permission.APPOINTMENT_CREATE]: "Create Appointment",
  [Permission.APPOINTMENT_APPROVE]: "Approve Appointment",
  [Permission.APPOINTMENT_RESCHEDULE]: "Reschedule Appointment",
  [Permission.APPOINTMENT_CANCEL]: "Cancel Appointment",
  [Permission.TICKET_VIEW]: "View Tickets",
  [Permission.TICKET_CREATE]: "Create Ticket",
  [Permission.TICKET_UPDATE]: "Update Ticket",
  [Permission.TICKET_CALL]: "Call Ticket",
  [Permission.TICKET_RECALL]: "Recall Ticket",
  [Permission.TICKET_SKIP]: "Skip Ticket",
  [Permission.TICKET_TRANSFER]: "Transfer Ticket",
  [Permission.TICKET_COMPLETE]: "Complete Ticket",
  [Permission.TICKET_CANCEL]: "Cancel Ticket",
  [Permission.ASSIGNMENT_VIEW]: "View Assignment",
  [Permission.ASSIGNMENT_ASSIGN_DOCTOR]: "Assign Doctor",
  [Permission.ASSIGNMENT_REASSIGN_DOCTOR]: "Reassign Doctor",
  [Permission.DOCTOR_VIEW]: "View Doctors",
  [Permission.DOCTOR_CREATE]: "Create Doctor",
  [Permission.DOCTOR_UPDATE]: "Edit Doctor",
  [Permission.DOCTOR_MANAGE_SCHEDULE]: "Manage Doctor Schedule",
  [Permission.DEPARTMENT_VIEW]: "View Departments",
  [Permission.DEPARTMENT_CREATE]: "Create Department",
  [Permission.DEPARTMENT_UPDATE]: "Edit Department",
  [Permission.QUEUE_CONFIG_VIEW]: "View Queue Configuration",
  [Permission.QUEUE_CONFIG_UPDATE]: "Update Queue Configuration",
  [Permission.CONTENT_VIEW]: "View Content",
  [Permission.CONTENT_CREATE]: "Create Content",
  [Permission.CONTENT_UPDATE]: "Edit Content",
  [Permission.CONTENT_PUBLISH]: "Publish Content",
  [Permission.USER_VIEW]: "View Users",
  [Permission.USER_CREATE]: "Create User",
  [Permission.USER_UPDATE]: "Edit User",
  [Permission.ROLE_VIEW]: "View Roles",
  [Permission.ROLE_CREATE]: "Create Role",
  [Permission.ROLE_UPDATE]: "Edit Role",
  [Permission.AUDIT_LOG_VIEW]: "View Audit Logs",
  [Permission.SYSTEM_SETTINGS_VIEW]: "View System Settings",
  [Permission.SYSTEM_SETTINGS_UPDATE]: "Update System Settings",
};

export const permissionGroups = [
  { label: "Dashboard", permissions: [Permission.DASHBOARD_VIEW] },
  { label: "Patient Management", permissions: [Permission.PATIENT_VIEW, Permission.PATIENT_CREATE, Permission.PATIENT_UPDATE] },
  { label: "Appointments", permissions: [Permission.APPOINTMENT_VIEW, Permission.APPOINTMENT_CREATE, Permission.APPOINTMENT_APPROVE, Permission.APPOINTMENT_RESCHEDULE, Permission.APPOINTMENT_CANCEL] },
  { label: "Queue / Ticketing", permissions: [Permission.TICKET_VIEW, Permission.TICKET_CREATE, Permission.TICKET_UPDATE, Permission.TICKET_CALL, Permission.TICKET_RECALL, Permission.TICKET_SKIP, Permission.TICKET_TRANSFER, Permission.TICKET_COMPLETE, Permission.TICKET_CANCEL] },
  { label: "Patient Assignment", permissions: [Permission.ASSIGNMENT_VIEW, Permission.ASSIGNMENT_ASSIGN_DOCTOR, Permission.ASSIGNMENT_REASSIGN_DOCTOR] },
  { label: "Doctors", permissions: [Permission.DOCTOR_VIEW, Permission.DOCTOR_CREATE, Permission.DOCTOR_UPDATE, Permission.DOCTOR_MANAGE_SCHEDULE] },
  { label: "Departments", permissions: [Permission.DEPARTMENT_VIEW, Permission.DEPARTMENT_CREATE, Permission.DEPARTMENT_UPDATE] },
  { label: "Queue Configuration", permissions: [Permission.QUEUE_CONFIG_VIEW, Permission.QUEUE_CONFIG_UPDATE] },
  { label: "Website", permissions: [Permission.CONTENT_VIEW, Permission.CONTENT_CREATE, Permission.CONTENT_UPDATE, Permission.CONTENT_PUBLISH] },
  { label: "Administration", permissions: [Permission.USER_VIEW, Permission.USER_CREATE, Permission.USER_UPDATE, Permission.ROLE_VIEW, Permission.ROLE_CREATE, Permission.ROLE_UPDATE, Permission.AUDIT_LOG_VIEW, Permission.SYSTEM_SETTINGS_VIEW, Permission.SYSTEM_SETTINGS_UPDATE] },
] as const;

export const defaultRolePermissions: Record<Role, Permission[]> = {
  [Role.IT_ADMIN]: Object.values(Permission),
  [Role.HOSPITAL_ADMIN]: [
    Permission.DASHBOARD_VIEW,
    Permission.PATIENT_VIEW,
    Permission.APPOINTMENT_VIEW,
    Permission.APPOINTMENT_APPROVE,
    Permission.APPOINTMENT_RESCHEDULE,
    Permission.APPOINTMENT_CANCEL,
    Permission.TICKET_VIEW,
    Permission.TICKET_CREATE,
    Permission.TICKET_UPDATE,
    Permission.TICKET_CALL,
    Permission.TICKET_RECALL,
    Permission.TICKET_SKIP,
    Permission.TICKET_TRANSFER,
    Permission.TICKET_COMPLETE,
    Permission.ASSIGNMENT_VIEW,
    Permission.ASSIGNMENT_ASSIGN_DOCTOR,
    Permission.ASSIGNMENT_REASSIGN_DOCTOR,
    Permission.DOCTOR_VIEW,
    Permission.DOCTOR_UPDATE,
    Permission.DOCTOR_MANAGE_SCHEDULE,
    Permission.DEPARTMENT_VIEW,
    Permission.DEPARTMENT_CREATE,
    Permission.DEPARTMENT_UPDATE,
    Permission.QUEUE_CONFIG_VIEW,
    Permission.QUEUE_CONFIG_UPDATE,
    Permission.AUDIT_LOG_VIEW,
  ],
  [Role.FRONT_DESK]: [Permission.DASHBOARD_VIEW, Permission.PATIENT_VIEW, Permission.PATIENT_CREATE, Permission.PATIENT_UPDATE, Permission.APPOINTMENT_VIEW, Permission.APPOINTMENT_CREATE, Permission.APPOINTMENT_RESCHEDULE, Permission.TICKET_VIEW, Permission.TICKET_CREATE],
  [Role.PATIENT_COORDINATOR]: [Permission.DASHBOARD_VIEW, Permission.PATIENT_VIEW, Permission.APPOINTMENT_VIEW, Permission.TICKET_VIEW, Permission.TICKET_CREATE, Permission.TICKET_UPDATE, Permission.TICKET_CALL, Permission.TICKET_RECALL, Permission.TICKET_SKIP, Permission.TICKET_TRANSFER, Permission.TICKET_COMPLETE, Permission.ASSIGNMENT_VIEW, Permission.ASSIGNMENT_ASSIGN_DOCTOR, Permission.ASSIGNMENT_REASSIGN_DOCTOR, Permission.DOCTOR_VIEW, Permission.DEPARTMENT_VIEW],
  [Role.DOCTOR]: [Permission.DASHBOARD_VIEW, Permission.PATIENT_VIEW, Permission.APPOINTMENT_VIEW, Permission.DOCTOR_VIEW],
  [Role.NURSE]: [Permission.DASHBOARD_VIEW, Permission.PATIENT_VIEW, Permission.TICKET_VIEW, Permission.TICKET_CALL, Permission.TICKET_RECALL, Permission.ASSIGNMENT_VIEW, Permission.DOCTOR_VIEW],
  [Role.RECORDS_STAFF]: [Permission.DASHBOARD_VIEW, Permission.PATIENT_VIEW],
  [Role.CONTENT_ADMIN]: [Permission.DASHBOARD_VIEW, Permission.CONTENT_VIEW, Permission.CONTENT_CREATE, Permission.CONTENT_UPDATE, Permission.CONTENT_PUBLISH],
  [Role.PATIENT]: [],
};
